
import cpoa.DBConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author valentinruiz
 */
public class InterfaceSupprimer extends javax.swing.JFrame {
    
    int Id = 0;
    Connection con = null;
    ResultSet rs = null;
    Statement stmt = null;
    int compteur = 0;
    
    /**
     * Creates new form InterfaceSupprimer
     */
    public InterfaceSupprimer() {
        initComponents();
    }

    public void save(int id){
        Id = id;
        update(Id);
    }
    
    private void update(int id){
        try {
            if(compteur == 0){
                con = DBConnection.connect();
                stmt = con.createStatement();

                String reuquete = "Select date from Entrainement where Player = '"+id+"' order by date DESC";

                rs = stmt.executeQuery(reuquete);
                Entrainement.removeAllItems();
                Entrainement.addItem("Selectionner un entrainement");
                Heure.removeAllItems();
                Heure.addItem(" Mettre à jour ");
                while(rs.next()){
                    Entrainement.addItem(rs.getString("date"));
                }
            }
            if (compteur == 1){
                con = DBConnection.connect();
                stmt = con.createStatement();
                String date = Entrainement.getSelectedItem().toString();
                
                String reuquete = "Select heure from Entrainement where Player = '"+id+"' and Entrainement.date = '"+date+"' order by date DESC";

                rs = stmt.executeQuery(reuquete);
                Heure.removeAllItems();
                Heure.addItem("Selectionner l'heure");
                while(rs.next()){
                    Heure.addItem(rs.getString("heure"));
                }
            }
           
        }
        catch(Exception e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Entrainement = new javax.swing.JComboBox<>();
        Retour = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Heure = new javax.swing.JComboBox<>();
        Maj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Supprimer un entrainement");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 90));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Choix de l'heure :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        Entrainement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrainementActionPerformed(evt);
            }
        });
        jPanel2.add(Entrainement, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        Retour.setText("Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });
        jPanel2.add(Retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 221, 111, -1));

        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });
        jPanel2.add(Supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 221, -1, -1));

        jLabel3.setText("Choix de l'entrainement :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        Heure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(Heure, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        Maj.setText("Mettre à jour");
        Maj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MajActionPerformed(evt);
            }
        });
        jPanel2.add(Maj, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 700, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrainementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrainementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntrainementActionPerformed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        // TODO add your handling code here:
            PlayerInterfaceHome pi = new PlayerInterfaceHome();
            pi.save(Id);
            pi.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_RetourActionPerformed

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        // TODO add your handling code here:
        try{
            String supprimer = Entrainement.getSelectedItem().toString();
            String heure = Heure.getSelectedItem().toString();
            
            String reuquete = "UPDATE Entrainement SET Player = null WHERE Entrainement.date = '"+supprimer+"' and Entrainement.heure = '"+heure+"' and Entrainement.Player = '"+Id+"'";
            stmt.executeUpdate(reuquete);
            
            update(Id);

        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_SupprimerActionPerformed

    private void MajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MajActionPerformed
        // TODO add your handling code here:
        compteur = 1;
        update(Id);
        compteur = 0;
    }//GEN-LAST:event_MajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceSupprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceSupprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceSupprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceSupprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceSupprimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Entrainement;
    private javax.swing.JComboBox<String> Heure;
    private javax.swing.JButton Maj;
    private javax.swing.JButton Retour;
    private javax.swing.JButton Supprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
